name: CI build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "testing"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC 64 Bit",
              os: windows-2022,
              environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
              generators: "Visual Studio 17 2022",
              msvc_arch: x64,
            }
          - {
              name: "Ubuntu Latest",
              os: ubuntu-latest,
              c_compiler: gcc,
              cpp_compiler: g++,
            }
          - {
              name: "Ubuntu Latest (Clang)",
              os: ubuntu-latest,
              c_compiler: clang,
              cpp_compiler: clang++,
            }
          - {
              name: "Mac OS Latest arm64",
              os: macos-latest,
              c_compiler: clang,
              cpp_compiler: clang++,
              osx_arch: arm64,
            }
    env:
      CMAKE_GENERATOR: "${{ matrix.config.generators }}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ilammy/setup-nasm@v1
      - run: git fetch --prune --unshallow
      - name: Ubuntu/Mac OS X
        if: ${{ !contains( matrix.config.generators, 'Visual Studio' ) }}
        run: |
          cmake --fresh -B Build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_CXX_COMPILER=${{ matrix.config.cpp_compiler }}" "-DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }}" -DNATIVE=ON -DSVT_AV1_LTO=ON -DBUILD_APPS=ON -DBUILD_DEC=OFF -DREPRODUCIBLE_BUILDS=ON "-DCMAKE_OSX_ARCHITECTURES=${{ matrix.config.osx_arch }}"
          cmake --build Build --config Release --parallel $(getconf _NPROCESSORS_ONLN 2> /dev/null || nproc 2> /dev/null || sysctl -n hw.ncpu 2> /dev/null)
        shell: bash
      - name: MSVC build
        if: contains( matrix.config.generators, 'Visual Studio' )
        run: |
          cmake -B Build -A "${{ matrix.config.msvc_arch }}" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_APPS=ON -DBUILD_DEC=OFF -DREPRODUCIBLE_BUILDS=ON
          cmake --build Build --config Release
        shell: cmd

      # --- 将最终文件上传为产物 ---

      - name: Upload Windows artifacts
        if: contains( matrix.config.generators, 'Visual Studio' )
        uses: actions/upload-artifact@v4
        with:
          name: svt-av1-win64
          path: Build/Release/*.exe

      - name: Upload Ubuntu artifacts
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: svt-av1-ubuntu-${{ matrix.config.c_compiler }}
          path: Build/SvtAv1EncApp

      - name: Upload Mac artifacts
        if: ${{ matrix.config.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: svt-av1-macos-arm64
          path: Build/SvtAv1EncApp
